apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds
  - ./falco
  - ./grafana
  - ./prometheus
  - ./test-pods
  - ./tetragon
  # Ensure ./nginx is NOT listed as a directory because it has no kustomization.yaml
  - ./nginx/deployment.yaml
  - ./nginx/service.yaml
