apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tetragonpolicies-crd.yaml
  - tetragontracepoints-crd.yaml
  - tracingpolicies-crd.yaml
  - tracingpoliciesnamespaced-crd.yaml
